run:
  input_csv: "enhance/output_enhance/greenSkillsCollection_enhanced.csv"
  predictions_out: "categorize/output_categorize/predictions_raw.csv"
  checkpoint: "categorize/output_categorize/checkpoint.jsonl"
  verbose_log: "categorize/output_categorize/verbose.log"
  seed: 42
  temperature: 0.0
  max_retries: 2
  id_col: conceptUri
  label_col: preferredLabel
  desc_col: description
  alt_col: altLabels

models:
  - name: llama3.1
    litellm_model: ollama_chat/llama3.1:8b
    supports_schema: false
    enabled: true
    api_base: mygpucluster1

  - name: gemma3.5
    litellm_model: ollama_chat/gemma3.5:9b
    supports_schema: false
    enabled: false
    api_base: mygpucluster1

  - name: gpt-oss
    litellm_model: ollama_chat/gpt-oss:20b
    supports_schema: false
    enabled: true
    api_base: mygpucluster1

